# Charles Buyas cjb8qf


print("Add two integers:", 4 + 4)
print("Add two strings:", "four" + "four")
print("Concatenate a string and an int or float:", "four" + str(4), "or", "four" + str(float(4)))
print("Replicate a string:", "four"*4)
print("Multiply two floating point numbers:", float(4.4*4.4))
print("Divide two floating point numbers:", float(8.0/6.0))
print("Raise an integer to an integer power:", 4 ** 4)
print("Raise a float to a float power:", 4.0 ** 4.0)
print("Find the remainder of 25 divided by 6:", 25 % 6)
print("Find if a number is even:", str(8 % 2))
print("Divide two integers, discarding the fractional amount:", 4 // 6)
print("Divide two integers:", 4/6)
print("Output an int coerced into a float:", float(4), 4 + 4.0)
print("Output a float coerced into an int:", int(4.0))
print("Output an int coerced into a string:", str(4))
print("Output an int concatenated to a string:", str(4) + "four")
print("Output 5.1234 with three places to the right of the decimal:", format(5.1234, '.3f'))
print("Output the data type of 7, '7', 7 + 7.0, and False:", type(7), type("7"), type(7 + 7.0), type(False))
print("Output an input string, an input int, and an input float:")
print(input("Input string: "))
print(int(input("Input int: ")))
print(float(input("Input float: ")))
print(eval(input("Please enter two comma separated numbers: ")))
print(eval(input("Please input a mathematical expression: ")))
print(len("Hello world"))
print(pow(int(input("Input a number: ")), 2))
list1 = input("Input comma separated numbers 1 to 100: ").split(",")
print("List is", list1)
add_ons = input("Do you want to add any more numbers?: ").split(",")
list2 = list1 + add_ons
print(list2)
